---

- host: all
  become: yes
  pre_tasks:

  - name: update & upgrade server
    apt:
      update_cache: yes
      upgrade: yes

  - name: copy the bash script to slave machine
    copy:
      src: laravel-slave.sh
      dest: ~/
      owner: root 
      group: root
      mode: 0744

  - name: Set Execute Permission on the Script
    command: chmod +x ~/laravel-slave.sh

  - name: Run Bash Script
    command: bash laravel-slave.sh dammy dammy120 < /dev/null 